version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy_forecast_api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    restart: unless-stopped

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    container_name: energy_forecast_frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
      - DATA_PATH=/app/energy_dataset.csv
    volumes:
      - ./energy_dataset.csv:/app/energy_dataset.csv
    depends_on:
      - api
    restart: unless-stopped